---
name: Config-Trivial
version: 0.51
author:
  - 'Adam Trickett, E<lt>atrickett@cpan.orgE<gt>'
abstract: Very simple tool for reading and writing very simple configuration files
license: gpl
requires:
  perl: 5.6.1
provides:
  Config::Trivial:
    file: lib/Config/Trivial.pm
    version: 0.51
generated_by: Module::Build version 0.26
