---
abstract: 'Very simple tool for reading and writing very simple configuration files'
author:
  - 'Adam Trickett, E<lt>atrickett@cpan.orgE<gt>'
build_requires:
  IO::Capture: '0'
  Module::Build: '0.4'
  Pod::Coverage: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
configure_requires:
  Module::Build: '0.40'
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.141170'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Trivial
provides:
  Config::Trivial:
    file: lib/Config/Trivial.pm
    version: '0.80'
requires:
  perl: '5.010'
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
version: '0.80'
